replicaCount: 1

image:
  repository: vladimirkhil/accountservice
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  labels: {}

ingress:
  enabled: false
  className: nginx
  clientSecret: ''
  annotations: {}
  hosts: []
  tls: []

resources: {}

database:
  host: postgres
  port: 5432
  name: account
  username: postgres
  passwordKey: ''
  passwordValue: 'postgres-password'
  backup:
    enabled: false
    schedule: '0 0 * * *' # Run every day at midnight
    imageVersion: 15
    securityContext: {}
    volumePath: ''

options:
  adminClientSecret: "change-me"
  steamApiKey: "change-me"
  steamAppId: "0"
  steamIdentity: "account-service"
  jwtIssuer: "AccountService"
  jwtAudience: "AccountConsumers"
  jwtPrivateKeyPem: ""
  jwtPublicKeyPem: ""
