apiVersion: v1
entries:
  account:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2026-07-19T09:19:00.7312811+02:00"
    description: Service for managing user accounts and authentication
    digest: f4aad231d2ce487aff88ada73715d118300f6db814d3e2b8b0ba280cc25a3c4a
    name: account
    type: application
    urls:
    - account-1.0.1.tgz
    version: 1.0.1
generated: "2026-07-19T09:19:00.7262675+02:00"
