apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accountservice.fullname" . }}
  labels:
    {{- include "accountservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "accountservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "accountservice.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ .Values.database.passwordKey }}'
                  key: '{{ .Values.database.passwordValue }}'
            - name: ConnectionStrings__AccountService
              value: 'Host={{ .Values.database.host }};Port={{ .Values.database.port }};Username={{ .Values.database.username }};Password=$(DBPASSWORD);Database={{ .Values.database.name }}'
            - name: Admin__ClientSecret
              value: {{ .Values.options.adminClientSecret | quote }}
            - name: Steam__ApiKey
              value: {{ .Values.options.steamApiKey | quote }}
            - name: Steam__AppId
              value: {{ .Values.options.steamAppId | quote }}
            - name: Steam__Identity
              value: {{ .Values.options.steamIdentity | quote }}
            - name: Jwt__Issuer
              value: {{ .Values.options.jwtIssuer | quote }}
            - name: Jwt__Audience
              value: {{ .Values.options.jwtAudience | quote }}
            - name: Jwt__PrivateKeyPem
              value: {{ .Values.options.jwtPrivateKeyPem | quote }}
            - name: Jwt__PublicKeyPem
              value: {{ .Values.options.jwtPublicKeyPem | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
