version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: accountservice-postgres
    environment:
      POSTGRES_DB: accountservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
